<Project Sdk="Uno.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\ProCharts.Uno\ProCharts.Uno.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFrameworks>net10.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>ProCharts.Uno.Gallery</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.procharts-uno-gallery</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>ProCharts.Uno.Gallery</ApplicationPublisher>
    <!-- Package Description -->
    <Description>ProCharts.Uno.Gallery powered by Uno Platform.</Description>

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      SkiaRenderer;
    </UnoFeatures>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

</Project>
